#version 430

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

subroutine void t_formatPickerStore(in ivec2 coord, in float result);
subroutine uniform t_formatPickerStore f_formatPickerStoreState;

layout(binding = 0) uniform sampler2D u_texSrc;
layout(binding = 1) uniform sampler2D u_texIn;
layout(binding = 0, r8) restrict writeonly uniform image2D u_texOut;
layout(binding = 1, r16) restrict writeonly uniform image2D u_texOut16;

uniform ivec3 u_sizeStep;
uniform ivec4 u_ioOffset;
uniform int u_vertical;
uniform vec2 u_gSigmaSRInv;

float getWeight(in float diff, in float i) {
    return exp(u_gSigmaSRInv.x * i * i + u_gSigmaSRInv.y * diff * diff);
}

subroutine(t_formatPickerStore) void p_bit8Store(in ivec2 coord, in float result) {
    imageStore(u_texOut, coord, vec4(result, vec3(0.0)));
}

subroutine(t_formatPickerStore) void p_bit16Store(in ivec2 coord, in float result) {
    imageStore(u_texOut16, coord, vec4(result, vec3(0.0)));
}

void main() {
    bool isVertical = bool(u_vertical);
    ivec4 pickOffset = isVertical ? ivec4(0, 0, u_ioOffset.zw) : ivec4(u_ioOffset.xy, 0, 0);
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_sizeStep.xy))) return;
    ivec2 samplingCoord = coord + pickOffset.xy;
    float center = texelFetch(u_texSrc, samplingCoord, 0).x;
    ivec2 checkSize = ivec2(0, isVertical ? u_sizeStep.y : u_sizeStep.x);
    ivec2 coordCurr;
    float curr, diff, sum = 0.0, weightCurr, weight = 0.0;
    for (int i = -u_sizeStep.z; i <= u_sizeStep.z; ++i) {
        coordCurr = samplingCoord + (isVertical ? ivec2(0, i) : ivec2(i, 0));
        checkSize.x = isVertical ? coordCurr.y : coordCurr.x;
        if (checkSize.x < 0 || checkSize.x >= checkSize.y) continue;
        curr = texelFetch(u_texIn, coordCurr, 0).x;
        diff = center - curr;
        weightCurr = getWeight(diff, float(i));
        sum += curr * weightCurr;
        weight += weightCurr;
    }
    f_formatPickerStoreState(coord + pickOffset.zw, sum / weight);
}