#version 430

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

subroutine void t_formatPickerStore(in ivec2 coord, in vec4 result);
subroutine uniform t_formatPickerStore f_formatPickerStoreState;

layout(binding = 0) uniform sampler2D u_texSrc;
layout(binding = 1) uniform sampler2D u_texIn;
layout(binding = 0, rgba8) restrict writeonly uniform image2D u_texOut;
layout(binding = 1, rgba16) restrict writeonly uniform image2D u_texOut16;

uniform ivec3 u_sizeStept16;
uniform ivec4 u_ioOffset;
uniform int u_vertical;
uniform vec2 u_gSigmaSRInv;

vec3 getWeight(in vec3 diff, in float i) {
    return exp(u_gSigmaSRInv.x * i * i + u_gSigmaSRInv.y * diff * diff);
}

subroutine(t_formatPickerStore) void p_bit8Store(in ivec2 coord, in vec4 result) {
    imageStore(u_texOut, coord, result);
}

subroutine(t_formatPickerStore) void p_bit16Store(in ivec2 coord, in vec4 result) {
    imageStore(u_texOut16, coord, result);
}

void main() {
    bool isVertical = bool(u_vertical);
    ivec4 pickOffset = isVertical ? ivec4(0, 0, u_ioOffset.zw) : ivec4(u_ioOffset.xy, 0, 0);
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_sizeStept16.xy))) return;
    ivec2 samplingCoord = coord + pickOffset.xy;
    vec4 center = texelFetch(u_texSrc, samplingCoord, 0);
    ivec2 checkSize = ivec2(0, isVertical ? u_sizeStept16.y : u_sizeStept16.x);
    ivec2 coordCurr;
    vec3 curr, diff, sum = vec3(0.0), weightCurr, weight = vec3(0.0);
    for (int i = -u_sizeStept16.z; i <= u_sizeStept16.z; ++i) {
        coordCurr = samplingCoord + (isVertical ? ivec2(0, i) : ivec2(i, 0));
        checkSize.x = isVertical ? coordCurr.y : coordCurr.x;
        if (checkSize.x < 0 || checkSize.x >= checkSize.y) continue;
        curr = texelFetch(u_texIn, coordCurr, 0).xyz;
        diff = center.xyz - curr;
        weightCurr = getWeight(diff, float(i));
        sum += curr * weightCurr;
        weight += weightCurr;
    }
    f_formatPickerStoreState(coord + pickOffset.zw, vec4(sum / weight, center.w));
}