#version 430

precision OVERWRITE_PRECISION float;
precision highp int;

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

subroutine void t_formatPickerStore(in ivec2 coord, in vec4 result);
subroutine uniform t_formatPickerStore f_formatPickerStoreState;
subroutine vec4 t_workMode(in ivec2 coord);
subroutine uniform t_workMode f_workModeState;

layout(binding = 0) uniform sampler2D u_texIn;
layout(binding = 0, rgba8) uniform writeonly image2D u_texOut;
layout(binding = 1, rgba16) uniform writeonly image2D u_texOut16;

uniform ivec3 u_sizeStep;
uniform int u_vertical;
uniform float u_perStep;

float getGaussian(float x) {
    float p = x * u_perStep;
    return u_perStep * 0.3989423 * exp(-0.5 * p * p);
}

subroutine(t_formatPickerStore) void p_bit8Store(in ivec2 coord, in vec4 result) {
    imageStore(u_texOut, coord, result);
}

subroutine(t_formatPickerStore) void p_bit16Store(in ivec2 coord, in vec4 result) {
    imageStore(u_texOut16, coord, result);
}

subroutine(t_workMode) vec4 filterMode(in ivec2 coord) {
    vec4 result = vec4(0.0);
    ivec2 maxIndex = u_sizeStep.xy - 1;
    ivec2 offset;
    float gaussian, fix = 0.0;
    bool isVertical = bool(u_vertical);
    for (int i = -u_sizeStep.z; i <= u_sizeStep.z; ++i) {
        gaussian = getGaussian(float(i));
        fix += gaussian;
        offset = isVertical ? ivec2(0, i) : ivec2(i, 0);
        result += texelFetch(u_texIn, clamp(offset + coord, ivec2(0), maxIndex), 0) * gaussian;
    }
    result /= fix;
    return result;
}

subroutine(t_workMode) vec4 copyMode(in ivec2 coord) {
    return texelFetch(u_texIn, coord, 0);
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_sizeStep.xy))) return;
    vec4 result = f_workModeState(coord);
    f_formatPickerStoreState(coord, result);
}