#version 430

precision OVERWRITE_PRECISION float;
precision highp int;

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

subroutine void t_formatPickerStore(in ivec2 coord, in vec4 result);
subroutine uniform t_formatPickerStore f_formatPickerStoreState;

layout(binding = 0) uniform isampler2D u_coordMap;
layout(binding = 0, r8) uniform writeonly image2D u_resultMap;
layout(binding = 1, r16) uniform writeonly image2D u_resultMapR16;

uniform ivec2 u_size;
uniform vec2 u_preMultiply;

subroutine(t_formatPickerStore) void p_bit8Store(in ivec2 coord, in vec4 result) {
    imageStore(u_resultMap, coord, result);
}

subroutine(t_formatPickerStore) void p_bit16Store(in ivec2 coord, in vec4 result) {
    imageStore(u_resultMapR16, coord, result);
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_size))) return;
    vec4 result = vec4(max(texelFetch(u_coordMap, coord, 0) - 1, 0) - coord.xyxy);
    float sdf = clamp(length(result.xy) * u_preMultiply.y, 0.0, 1.0) - clamp(length(result.zw) * u_preMultiply.x, 0.0, 1.0);
    result = vec4(clamp(fma(sdf, 0.5, 0.5), 0.0, 1.0), vec3(0.0));
    f_formatPickerStoreState(coord, result);
}