#version 430

#define MAX_DISTANCE 268435456.0

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) uniform usampler2D u_coordMapIn;
layout(binding = 0, rgba16ui) restrict writeonly uniform uimage2D u_coordMapOut;

uniform ivec2 u_size;
uniform int u_step;

uvec4 advanceJFA(in ivec2 coord) {
    ivec4 result = ivec4(0);

    ivec2 currCoord = ivec2(0);
    vec2 distSQ = vec2(MAX_DISTANCE);
    for (int y = -1; y <= 1; ++y) {
        currCoord.y = y * u_step + coord.y;
        for (int x = -1; x <= 1; ++x) {
            currCoord.x = x * u_step + coord.x;
            if (any(bvec4(lessThan(currCoord, ivec2(0)), greaterThanEqual(currCoord, u_size)))) continue;
            ivec4 targetCoord = ivec4(texelFetch(u_coordMapIn, currCoord, 0)) - 1;

            if (targetCoord.x > -1) {
                vec2 currDiff = vec2(coord - targetCoord.xy);
                float currDistSQ = dot(currDiff, currDiff);
                if (currDistSQ < distSQ.x) {
                    distSQ.x = currDistSQ;
                    result.xy = targetCoord.xy + 1;
                }
            }
            if (targetCoord.z > -1) {
                vec2 currDiff = vec2(coord - targetCoord.zw);
                float currDistSQ = dot(currDiff, currDiff);
                if (currDistSQ < distSQ.y) {
                    distSQ.y = currDistSQ;
                    result.zw = targetCoord.zw + 1;
                }
            }
        }
    }
    return uvec4(result);
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_size))) return;
    imageStore(u_coordMapOut, coord, advanceJFA(coord));
}