#version 430

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

subroutine float t_sampleMethod(in ivec2 sampleCoord);
subroutine uniform t_sampleMethod f_sampleMethodState;

layout(binding = 0) uniform sampler2D u_checkMap;
layout(binding = 0, rgba16i) restrict writeonly uniform iimage2D u_resultMap;

uniform ivec4 u_sizeState; // ivec2(checkMapSize), ivec2(resultMapSize)
uniform ivec4 u_border_offset;
uniform float u_threshold;

subroutine(t_sampleMethod) float p_fromRed(in ivec2 sampleCoord) {
    return texelFetch(u_checkMap, sampleCoord, 0).x;
}

subroutine(t_sampleMethod) float p_fromGreen(in ivec2 sampleCoord) {
    return texelFetch(u_checkMap, sampleCoord, 0).y;
}

subroutine(t_sampleMethod) float p_fromBlue(in ivec2 sampleCoord) {
    return texelFetch(u_checkMap, sampleCoord, 0).z;
}

subroutine(t_sampleMethod) float p_fromAlpha(in ivec2 sampleCoord) {
    return texelFetch(u_checkMap, sampleCoord, 0).w;
}

subroutine(t_sampleMethod) float p_fromRGB(in ivec2 sampleCoord) {
    return dot(texelFetch(u_checkMap, sampleCoord, 0).xyz, vec3(LINEAR_VALUES));
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_sizeState.zw))) return;
    ivec2 coordStore = ivec2(coord + 1);
    ivec2 checkCoord = coord - u_border_offset.xy;
    ivec4 result;
    if (all(bvec4(greaterThanEqual(coord, u_border_offset.xy), lessThan(checkCoord, u_sizeState.xy)))) {
        result = (f_sampleMethodState(checkCoord + u_border_offset.zw) >= u_threshold) ? ivec4(coordStore, 0, 0) : ivec4(0, 0, coordStore);
    } else result = ivec4(0, 0, coordStore);
    imageStore(u_resultMap, coord, result);
}