#version 430

#define RADIUS_SCALE OVERWRITE_RADIUS_SCALE

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

subroutine vec4 t_sampleMode(in ivec2 coord);
subroutine uniform t_sampleMode f_sampleModeState;

layout (binding = 0) uniform sampler2D u_texIn;
layout (binding = 1) uniform sampler2D u_texHL;
layout (binding = 0, rgb10_a2) restrict writeonly uniform image2D u_texOut;
layout (binding = 1, rgba8) restrict writeonly uniform image2D u_texOutFirst;

uniform ivec2 u_size;
uniform vec4 u_targetUVStepDiv;
uniform int u_initPass;

const vec2 downCoord[] = vec2[4](
vec2(-1.0, -1.0) * RADIUS_SCALE, vec2(1.0, -1.0) * RADIUS_SCALE, vec2(-1.0, 1.0) * RADIUS_SCALE, vec2(1.0, 1.0) * RADIUS_SCALE
);

const vec2 upCoordA[] = vec2[4](
vec2(0.0, -2.0) * RADIUS_SCALE, vec2(-2.0, 0.0) * RADIUS_SCALE, vec2(2.0, 0.0) * RADIUS_SCALE, vec2(0.0, 2.0) * RADIUS_SCALE
);

const vec2 upCoordB[] = vec2[4](
vec2(-1.0, -1.0) * RADIUS_SCALE, vec2(1.0, -1.0) * RADIUS_SCALE, vec2(-1.0, 1.0) * RADIUS_SCALE, vec2(1.0, 1.0) * RADIUS_SCALE
);

subroutine(t_sampleMode) vec4 p_sampleInit(in ivec2 coord) {
	return max(texelFetch(u_texIn, coord, 0), texelFetch(u_texHL, coord, 0));
}

subroutine(t_sampleMode) vec4 p_downSampleFirst(in ivec2 coord) {
	vec2 uv = vec2(coord) * u_targetUVStepDiv.zw;
	vec3 result = texture(u_texIn, uv).xyz, resultA, weight;
	weight = result * 0.4;
	weight = fma(texture(u_texIn, fma(u_targetUVStepDiv.xy, vec2(-1.0, -1.0), uv)).xyz, vec3(0.15), weight);
	weight = fma(texture(u_texIn, fma(u_targetUVStepDiv.xy, vec2(1.0, -1.0), uv)).xyz, vec3(0.15), weight);
	weight = fma(texture(u_texIn, fma(u_targetUVStepDiv.xy, vec2(-1.0, 1.0), uv)).xyz, vec3(0.15), weight);
	weight = fma(texture(u_texIn, fma(u_targetUVStepDiv.xy, vec2(1.0, 1.0), uv)).xyz, vec3(0.15), weight);

	resultA = texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[0], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[1], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[2], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[3], uv)).xyz;

	resultA *= 0.125;
	result = fma(result, vec3(0.5), resultA);
	return vec4(result / (0.6666667 + dot(weight, vec3(0.2126729, 0.7151522, 0.0721750))), 1.0);
}

subroutine(t_sampleMode) vec4 p_downSample(in ivec2 coord) {
	vec2 uv = vec2(coord) * u_targetUVStepDiv.zw;
	vec3 result = texture(u_texIn, uv).xyz, resultA;

	resultA = texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[0], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[1], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[2], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, downCoord[3], uv)).xyz;

	resultA *= 0.125;
	return vec4(fma(result, vec3(0.5), resultA), 1.0);
}

subroutine(t_sampleMode) vec4 p_upSample(in ivec2 coord) {
	vec2 uv = vec2(coord) * u_targetUVStepDiv.zw;
	vec3 result = texelFetch(u_texHL, coord, 0).xyz, resultA, resultB;

	resultA = texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordA[0], uv)).xyz;
	resultB = texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordB[0], uv)).xyz;
	resultB += texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordB[1], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordA[1], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordA[2], uv)).xyz;
	resultB += texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordB[2], uv)).xyz;
	resultB += texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordB[3], uv)).xyz;
	resultA += texture(u_texIn, fma(u_targetUVStepDiv.xy, upCoordA[3], uv)).xyz;

	resultB *= 0.1666667;
	result += fma(resultA, vec3(0.0833333), resultB);
	return vec4(result, 1.0);
}

void main() {
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	if (any(greaterThanEqual(coord, u_size))) return;
	vec4 result = f_sampleModeState(coord);
	if (bool(u_initPass)) imageStore(u_texOutFirst, coord, result); else imageStore(u_texOut, coord, result);
}
