#version 430

#define PI2 6.2831853

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

struct ComplexArray {
    vec2 red;
    vec2 green;
    vec2 blue;
    vec2 alpha;
};

subroutine void t_formatPickerStore(in ivec2 coord, in ComplexArray result, in bool isGenRGBA);
subroutine uniform t_formatPickerStore f_formatPickerStoreState;

layout(binding = 0) uniform sampler2D u_texIn;
layout(binding = 0, rgba8) restrict writeonly uniform image2D u_texOut;
layout(binding = 1, rgba16f) restrict writeonly uniform image2D u_texOut16;
layout(binding = 2, rgba32f) restrict writeonly uniform image2D u_texOut32;

uniform ivec4 u_ioOffset;
uniform ivec2 u_size;
uniform int u_state; // 0b1 = inverse, 0b10 = vertical, 0b100 = genFromRGBA, 0b1000 = genRGBA, 0b10000 = outputStage
uniform vec2 u_sizeDiv;

vec2 getEuler(in float theta) {
    return vec2(cos(theta), sin(theta));
}

vec2 cmul(in vec2 left, in vec2 right)
{
    return vec2(left.x * right.x - left.y * right.y, left.x * right.y + left.y * right.x);
}

subroutine(t_formatPickerStore) void p_bit8Store(in ivec2 coord, in ComplexArray result, in bool isGenRGBA) {
    vec4 resultStore = isGenRGBA ? vec4(length(result.red), length(result.green), length(result.blue), length(result.alpha)) : vec4(result.red, result.green);
    imageStore(u_texOut, coord, resultStore);
    if (!isGenRGBA) imageStore(u_texOut, ivec2(coord.x + u_size.x, coord.y), vec4(result.blue, result.alpha));
}

subroutine(t_formatPickerStore) void p_bit16Store(in ivec2 coord, in ComplexArray result, in bool isGenRGBA) {
    vec4 resultStore = isGenRGBA ? vec4(length(result.red), length(result.green), length(result.blue), length(result.alpha)) : vec4(result.red, result.green);
    imageStore(u_texOut16, coord, resultStore);
    if (!isGenRGBA) imageStore(u_texOut16, ivec2(coord.x + u_size.x, coord.y), vec4(result.blue, result.alpha));
}

subroutine(t_formatPickerStore) void p_bit32Store(in ivec2 coord, in ComplexArray result, in bool isGenRGBA) {
    vec4 resultStore = isGenRGBA ? vec4(length(result.red), length(result.green), length(result.blue), length(result.alpha)) : vec4(result.red, result.green);
    imageStore(u_texOut32, coord, resultStore);
    if (!isGenRGBA) imageStore(u_texOut32, ivec2(coord.x + u_size.x, coord.y), vec4(result.blue, result.alpha));
}

ComplexArray transformHFromRGBA(in ivec2 coord, in float centerCoord) {
    float theta, coordF = PI2 * centerCoord * u_sizeDiv.x;
    vec2 euler;
    vec4 raw;
    ComplexArray result = ComplexArray(vec2(0.0), vec2(0.0), vec2(0.0), vec2(0.0));
    for (int n = 0; n < u_size.x; ++n) {
        theta = float(n) * coordF;
        euler = getEuler(theta);
        raw = texelFetch(u_texIn, ivec2(n, coord.y), 0);
        result.red += cmul(vec2(raw.x, 0.0), euler);
        result.green += cmul(vec2(raw.y, 0.0), euler);
        result.blue += cmul(vec2(raw.z, 0.0), euler);
        result.alpha += cmul(vec2(raw.w, 0.0), euler);
    }
    return result;
}

ComplexArray transformH(in ivec2 coord, in float pi, in float centerCoord) {
    float theta, coordF = pi * centerCoord * u_sizeDiv.x;
    int coordSub = u_size.x;
    vec2 euler;
    vec4 comp;
    ComplexArray result = ComplexArray(vec2(0.0), vec2(0.0), vec2(0.0), vec2(0.0));
    for (int n = 0; n < u_size.x; ++n) {
        theta = float(n) * coordF;
        euler = getEuler(theta);
        comp = texelFetch(u_texIn, ivec2(n, coord.y), 0);
        result.red += cmul(comp.xy, euler);
        result.green += cmul(comp.zw, euler);
        comp = texelFetch(u_texIn, ivec2(coordSub, coord.y), 0);
        result.blue += cmul(comp.xy, euler);
        result.alpha += cmul(comp.zw, euler);
        ++coordSub;
    }
    return result;
}

ComplexArray transformV(in ivec2 coord, in float pi, in float centerCoord) {
    float theta, coordF = pi * centerCoord * u_sizeDiv.y;
    int coordSub = coord.x + u_size.x;
    vec2 euler;
    vec4 comp;
    ComplexArray result = ComplexArray(vec2(0.0), vec2(0.0), vec2(0.0), vec2(0.0));
    for (int n = 0; n < u_size.y; ++n) {
        theta = float(n) * coordF;
        euler = getEuler(theta);
        comp = texelFetch(u_texIn, ivec2(coord.x, n), 0);
        result.red += cmul(comp.xy, euler);
        result.green += cmul(comp.zw, euler);
        comp = texelFetch(u_texIn, ivec2(coordSub, n), 0);
        result.blue += cmul(comp.xy, euler);
        result.alpha += cmul(comp.zw, euler);
    }
    return result;
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_size))) return;
    bool isInverse = (u_state & 1) > 0, isVertical = (u_state & 2) > 0, isGenFromRGBA = (u_state & 4) > 0, isGenRGBA = (u_state & 8) > 0, isOutputStage = (u_state & 16) > 0;
    ivec4 pickOffset = isOutputStage ? ivec4(0, 0, u_ioOffset.zw) : ivec4(u_ioOffset.xy, 0, 0);
    vec2 centerCoord = isVertical ? vec2(coord.y, u_size.y) : vec2(coord.x, u_size.x);
    if (!isInverse) centerCoord.x -= centerCoord.y * 0.5;

    float pi = isInverse ? -PI2 : PI2;
    ComplexArray result = ComplexArray(vec2(0.0), vec2(0.0), vec2(0.0), vec2(0.0));
    if (isGenFromRGBA) {
        result = transformHFromRGBA(coord + pickOffset.xy, centerCoord.x);
    } else {
        result = isVertical ? transformV(coord + pickOffset.xy, pi, centerCoord.x) : transformH(coord, pi, centerCoord.x);
    }
    if (isInverse) {
        vec2 div = vec2(isVertical ? u_sizeDiv.y : u_sizeDiv.x);
        result.red *= div;
        result.green *= div;
        result.blue *= div;
        result.alpha *= div;
    }
    f_formatPickerStoreState(coord + pickOffset.zw, result, isGenRGBA);
}