#version 430

#define PI2 6.2831853

layout(local_size_x = RESET_VALUE, local_size_y = 8, local_size_z = 1) in;

subroutine void t_formatPickerStore(in ivec2 coord, in vec2 result, in bool isGenRed);
subroutine uniform t_formatPickerStore f_formatPickerStoreState;

layout(binding = 0) uniform sampler2D u_texIn;
layout(binding = 0, r8) restrict writeonly uniform image2D u_texOut;
layout(binding = 1, r16f) restrict writeonly uniform image2D u_texOut16;
layout(binding = 2, r32f) restrict writeonly uniform image2D u_texOut32;

uniform ivec4 u_ioOffset;
uniform ivec2 u_size;
uniform int u_state; // 0b1 = inverse, 0b10 = vertical, 0b100 = genFromRed, 0b1000 = genRed;
uniform vec2 u_sizeDiv;

vec2 getEuler(in float theta) {
    return vec2(cos(theta), sin(theta));
}

vec2 cmul(in vec2 left, in vec2 right)
{
    return vec2(left.x * right.x - left.y * right.y, left.x * right.y + left.y * right.x);
}

subroutine(t_formatPickerStore) void p_bit8Store(in ivec2 coord, in vec2 result, in bool isGenRed) {
    vec4 resultStore = isGenRed ? vec4(length(result), vec3(0.0)) : vec4(result.x, vec3(0.0));
    imageStore(u_texOut, coord, resultStore);
    if (!isGenRed) imageStore(u_texOut, ivec2(coord.x + u_size.x, coord.y), vec4(result.y, vec3(0.0)));
}

subroutine(t_formatPickerStore) void p_bit16Store(in ivec2 coord, in vec2 result, in bool isGenRed) {
    vec4 resultStore = isGenRed ? vec4(length(result), vec3(0.0)) : vec4(result.x, vec3(0.0));
    imageStore(u_texOut16, coord, resultStore);
    if (!isGenRed) imageStore(u_texOut16, ivec2(coord.x + u_size.x, coord.y), vec4(result.y, vec3(0.0)));
}

subroutine(t_formatPickerStore) void p_bit32Store(in ivec2 coord, in vec2 result, in bool isGenRed) {
    vec4 resultStore = isGenRed ? vec4(length(result), vec3(0.0)) : vec4(result.x, vec3(0.0));
    imageStore(u_texOut32, coord, resultStore);
    if (!isGenRed) imageStore(u_texOut32, ivec2(coord.x + u_size.x, coord.y), vec4(result.y, vec3(0.0)));
}

vec2 transformHFromRed(in ivec2 coord, in float centerCoord) {
    float theta, coordF = PI2 * centerCoord * u_sizeDiv.x;
    vec2 euler;
    vec2 result = vec2(0.0);
    for (int n = 0; n < u_size.x; ++n) {
        theta = float(n) * coordF;
        euler = getEuler(theta);
        result += cmul(vec2(texelFetch(u_texIn, ivec2(n, coord.y), 0).x, 0.0), euler);
    }
    return result;
}

vec2 transformH(in ivec2 coord, in float pi, in float centerCoord) {
    float theta, coordF = pi * centerCoord * u_sizeDiv.x;
    int coordSub = u_size.x;
    vec2 euler;
    vec2 comp = vec2(0.0);
    vec2 result = vec2(0.0);
    for (int n = 0; n < u_size.x; ++n) {
        theta = float(n) * coordF;
        euler = getEuler(theta);
        comp.x = texelFetch(u_texIn, ivec2(n, coord.y), 0).x;
        comp.y = texelFetch(u_texIn, ivec2(coordSub, coord.y), 0).x;
        result += cmul(comp, euler);
        ++coordSub;
    }
    return result;
}

vec2 transformV(in ivec2 coord, in float pi, in float centerCoord) {
    float theta, coordF = pi * centerCoord * u_sizeDiv.y;
    int coordSub = coord.x + u_size.x;
    vec2 euler;
    vec2 comp = vec2(0.0);
    vec2 result = vec2(0.0);
    for (int n = 0; n < u_size.y; ++n) {
        theta = float(n) * coordF;
        euler = getEuler(theta);
        comp.x = texelFetch(u_texIn, ivec2(coord.x, n), 0).x;
        comp.y = texelFetch(u_texIn, ivec2(coordSub, n), 0).x;
        result += cmul(comp, euler);
    }
    return result;
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(coord, u_size))) return;
    bool isInverse = (u_state & 1) > 0, isVertical = (u_state & 2) > 0, isGenFromRed = (u_state & 4) > 0, isGenRed = (u_state & 8) > 0, isOutputStage = (u_state & 16) > 0;
    ivec4 pickOffset = isOutputStage ? ivec4(0, 0, u_ioOffset.zw) : ivec4(u_ioOffset.xy, 0, 0);
    vec2 centerCoord = isVertical ? vec2(coord.y, u_size.y) : vec2(coord.x, u_size.x);
    if (!isInverse) centerCoord.x -= centerCoord.y * 0.5;

    float pi = isInverse ? -PI2 : PI2;
    vec2 result = vec2(0.0);
    if (isGenFromRed) {
        result = transformHFromRed(coord + pickOffset.xy, centerCoord.x);
    } else {
        result = isVertical ? transformV(coord + pickOffset.xy, pi, centerCoord.x) : transformH(coord, pi, centerCoord.x);
    }
    if (isInverse) {
        vec2 div = vec2(isVertical ? u_sizeDiv.y : u_sizeDiv.x);
        result *= div;
    }
    f_formatPickerStoreState(coord + pickOffset.zw, result, isGenRed);
}